# INDIAN STARTUP FUNDING

**SECTION - A (QUESTIONS)**

**Q1.** What's the difference between a Series and a DataFrame? Give one operation that works on both,and one that works only on a DataFrame.

**Q2.** What does inplace=True do? Why is the pandas team discouraging its use in newer versions? Give one example where you'd avoid it.

**Q3.** Explain the difference between .fillna() and .dropna(). When would a data analyst pick one over theother? Be specific - give a concrete situation for each.

**Q4.** What does pd.to_numeric(col, errors='coerce') do that plain pd.to_numeric(col) does NOT? Which one would you use on real-world messy data, and why?

**Q5.** Explain .loc vs .iloc with one example each. Then describe a case where df.loc[0] and df.iloc[0] return different rows.

**Q6.** What is the difference between .map(), .apply(), and .replace() for a Series? When would you reach for each?

**Q7.** What is the SettingWithCopyWarning? Give one example of code that triggers it and one way to fix it. (Hint: the chained-assignment pattern.)

**Q8.** Explain pd.cut() vs pd.qcut(). If you have annual income data and want to label customers as Low /Mid / High earners, which one fits better? Why?

**SECTION - A (ANSWERS)**

**Q1.** Series is more like a continuous collecton of elements like arrays whereas a dataframe is two-dimension which consists of rows and columns.

**.describe()** operation works on both series and dataframe.

**.drop(columns=[])** operation works only on a dataframe

**Q2.** inplace=True makes sure the changes done are reflected on the original dataframe

**Main reason for me is because inplace=True can be run only once**
        
**While doing changes to the original dataframe**

**Q3.** **.fillna()** is used to fill the missing,error,null values in a column,
        **.dropna()** is used to drop null values
Picking one over another isnt the main thing it completely depends on the type of data they are working on.

For example:If a employeeID is missing in the employee database then doing dropna() makes the row completely useless so its necessary to choose the important operation based on the dataset we are working on

**Q4.** **pd.to_numeric(col,errors='coerce')** forces the text which can't be converted into NaN. I would use **pd.to_numeric(col,errors='coerce')** because it can handle all the formats that can't be converted into numbers.

**Q5.**
        Ex:df.loc(0,[['Survived','PClass']])
        
        Ex:df.iloc(0,[0,1,2])

        df.loc[0] - returns the row labeled as index 0 whereas
        df.iloc[0] - returns the first row regardless of the label

**Q6.** **.map()** - it is used for mapping using categories

**.apply()** - to do mathematical calculations which are complex

**.replace()** - Used to replace an existing value or values based on conditions

**Q7.** This topic 'SettingWithCopyWarning' is not taught to us in the online classes so unable to answer using google
**"The SettingWithCopyWarning is a warning pandas raises when you try to modify data that might be a temporary "copy" rather than the original DataFrame. When this happens, your changes might disappear or accidentally overwrite the wrong data"**

**Q8.** pd.cut() and pd.qcut() is not taught to us in the online classes so i'm unaware of it so i'll learn about these functions online and write it in my own way of how i understood

**pd.cut()** - seperate data based on equal width intervals whereas
**pd.qcut()** - seperate data based on equal-sized buckets

**pd.cut()** fits better for labelling customers because income is highly skewed

# **Section B – Predict the Output**

**After Predicting the output the corresponding code has been executed**

**Q9.Predict the output. What's in df at the end?**

    import pandas as pd
    df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
    df2 = df
    df2['a'] = [10, 20, 30]
    print(df)

**Predicted Output**
'''

       a  b    
    0  10  4
    1  20  5
    2  30  6
'''

In [284]:
import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
df2 = df
df2['a'] = [10, 20, 30]
print(df)

    a  b
0  10  4
1  20  5
2  30  6

**Q10. Predict both outputs.**

    import pandas as pd
    import numpy as np
    s = pd.Series([1, 2, np.nan, 4, 5])
    print(s.mean())
    print(s.sum())

**Predicted Output**

    3
    12

In [ ]:
import pandas as pd
import numpy as np
s = pd.Series([1, 2, np.nan, 4, 5])
print(s.mean())
print(s.sum())

**Q11. Predict the dtype and the sum.**

    import pandas as pd
    df = pd.DataFrame({'price': ['100', '200', 'NA', '400']})
    df['price'] = pd.to_numeric(df['price'], errors='coerce')
    print(df['price'].dtype)
    print(df['price'].sum())

**Predicted Output**

      float
      700.0

In [ ]:
import pandas as pd
df = pd.DataFrame({'price': ['100', '200', 'NA', '400']})
df['price'] = pd.to_numeric(df['price'], errors='coerce')
print(df['price'].dtype)
print(df['price'].sum())

**Q12. Predict the type of df.loc[0].**

    import pandas as pd
    df = pd.DataFrame({'name': ['Rahul', 'Priya'], 'age': [22, 21]})
    print(df.loc[0])
    print(type(df.loc[0]))

**Predicted Output**

      name  Rahul
      age   22
      dtype:object

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['Rahul', 'Priya'], 'age': [22, 21]})
print(df.loc[0])
print(type(df.loc[0]))

**Q13. Predict – and explain what's wrong with the modification line.**

    import pandas as pd
    df = pd.DataFrame({'rating': [4.5, 3.8, 4.2, 5.0]})
    df_filtered = df[df['rating'] > 4]
    df_filtered['rating'] = df_filtered['rating'] * 2 # what warning?
    print(df)
    print(df_filtered)

**Predicted Output**

       rating
    0     4.5
    1     3.8
    2     4.2
    3     5.0

       rating
    0     9.0
    2     8.4
    3    10.0

    Coul'dnt find whats wrong with the modification line

In [ ]:
import pandas as pd
df = pd.DataFrame({'rating': [4.5, 3.8, 4.2, 5.0]})
df_filtered = df[df['rating'] > 4]
df_filtered['rating'] = df_filtered['rating'] * 2 # what warning?
print(df)
print(df_filtered)

**Q14. Predict the result AND its dtype. Why is the dtype what it is?**

    import pandas as pd
    df = pd.DataFrame({'a': [1, 2, 3, 4]})
    result = df['a'].apply(lambda x: x**2 if x > 2 else 'small')
    print(result)
    print(result.dtype)

**Predicted Output**

    0    small
    1    small
    2      9
    3     16
    dtype:object

In [ ]:
import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3, 4]})
result = df['a'].apply(lambda x: x**2 if x > 2 else 'small')
print(result)
print(result.dtypes)

**Q15. Predict each output. What's the difference between nunique(), len(unique()), and value_counts()?**

  import pandas as pd

  df = pd.DataFrame({'city': ['Delhi', 'Mumbai', 'Delhi', 'Bengaluru', None]})

  print(df['city'].nunique())

  print(len(df['city'].unique()))
  
  print(df['city'].value_counts())


**Predicted Output**

    3
    4
    Delhi 2
    Mumbai 1
    Bangalore 1

**nunique()** gives the number of unique values

**len(unique)** - gives the number of distinct items

**value_counts** - gives the total count of all the repeated distinct values

In [ ]:
import pandas as pd
df = pd.DataFrame({'city': ['Delhi', 'Mumbai', 'Delhi', 'Bengaluru', None]})
print(df['city'].nunique())
print(len(df['city'].unique()))
print(df['city'].value_counts())

**Q16. Predict each line. The commented line will throw an error or silently break — explain why.**

    import pandas as pd

    df = pd.DataFrame({'a': [1, 2, 3], 'b': [10, 20, 30]})

    print(df[df['a'] > 1])

    ** print(df[df['a'] > 1 & df['b'] > 15]) # <-- what's wrong here **
    print(df[(df['a'] > 1) & (df['b'] > 15)])

**Predicted Output**

       a   b
    1  2   20
    2  3   30

       a   b
    1  2  20
    2  3  30     

**The commented line throw an error because when using & operator they have not usede the common brackets properly so it is not able to understand the two conditions**

In [286]:
import pandas as pd

df = pd.DataFrame({'a': [1, 2, 3], 'b': [10, 20, 30]})
print(df[df['a'] > 1])
#print(df[df['a'] > 1 & df['b'] > 15]) # <-- what's wrong here **
print(df[(df['a'] > 1) & (df['b'] > 15)])

   a   b
1  2  20
2  3  30
   a   b
1  2  20
2  3  30

# **Section C – Applied on Indian Startups Dataset**

**The cleaning expected of you (do this ONCE at the top of Section C).**

**1. Rename columns to clean snake_case: startup_name, city, industry, funding_stage, amount,funding_date, investors, founded_year.**

**2. Clean startup_name and city - strip whitespace, title case.**

**3. Standardise city aliases: Bangalore / BLR → Bengaluru; Bombay → Mumbai; Gurgaon → Gurugram; Delhi → New Delhi; Calcutta → Kolkata; Madras → Chennai.**

**4. Standardise industry and funding_stage variants using dicts.**

**5. Convert amount to numeric (in INR Cr): strip ₹, INR, Cr, Crore, commas, then pd.to_numeric(errors='coerce'). 'Undisclosed' should become NaN.**

**6. Convert funding_date to datetime with errors='coerce' and dayfirst=True.**

**7. Drop duplicate rows.**

**Use this cleaned df for every question that follows. Anyone who skips cleaning cannot answer Q22 onwards correctly.**

In [212]:
import pandas as pd

df = pd.read_csv('indian_startups_fundingDADS.csv')
df

,Startup Name,City,INDUSTRY,Funding Stage,Amount,Funding Date,Investors,Founded Year
0,PlayTime Games,DELHI,ecommerce,Series-E,INR 942 Crore,29/02/2024,"Ranjan Pai, Prosus Ventures",2020.0
1,Rebel Foods,ahmedabad,BeautyTech,Pre-A,1440,18/08/2018,Lightspeed,2017.0
2,Freshworks,Kolkata,AgriTech,Pre-Series A,329 Cr,14 Jul 2020,Info Edge,2020.0
3,BigBasket,Mumbai,ecommerce,Series D,₹1405 Cr,31/03/2018,B Capital,2016.0
4,Ola,KOLKATA,EdTech,SERIES E,₹2223 Cr,24-08-2021,Falcon Edge,2017.0
...,...,...,...,...,...,...,...,...
463,Doubtnut,KOLKATA,ecommerce,Seed,88 Cr,09/07/2012,"Elevation Capital, Chiratae Ventures",2010.0
464,EcoMotor,KOLKATA,HealthTech,Seed,₹41 Cr,01-03-2019,"Goldman Sachs, 3one4 Capital, Elevation Capita...",2008.0
465,Zepto,CHENNAI,AI-ML,Bridge,24 Cr,2023/11/24,"Blume Ventures, Inventus Capital",2018.0
466,FastTrack Logistics,KOLKATA,Agri Tech,bridge,INR 700 Crore,08 Dec 2019,"Matrix Partners, Blume Ventures",2018.0
467,Freshworks,Calcutta,fintech,seed,₹468 Cr,NaN,"Norwest Venture, Elevation Capital, Blume Vent...",2016.0

**1. Rename columns to clean snake_case: startup_name, city, industry, funding_stage, amount,funding_date, investors, founded_year.**

In [213]:
df =df.rename(columns = {
    'Startup Name ':'startup_name',
    'City':'city',
    'INDUSTRY':'industry',
    'Funding Stage':'funding_stage',
    'Amount':'amount',
    'Funding Date':'funding_date',
    'Investors':'investors',
    'Founded Year':'founded_year'
})

**2. Clean startup_name and city - strip whitespace, title case.**

In [214]:
df['startup_name'] = df['startup_name'].str.strip().str.replace(' ','').str.title()
df['city'] = df['city'].str.strip().str.replace(' ','').str.title()

In [215]:
df['startup_name'].sample(10)

205       Docontime
79       Rebelfoods
1        Rebelfoods
98           Meesho
341          Practo
122           Mediq
225    Smartscholar
18      Wellnesshub
262          Inmobi
298        Edusmart
Name: startup_name, dtype: object

**3. Standardise city aliases: Bangalore / BLR → Bengaluru; Bombay → Mumbai; Gurgaon → Gurugram; Delhi → New Delhi; Calcutta → Kolkata; Madras → Chennai.**

In [216]:
df['city'].unique()

array(['Delhi', 'Ahmedabad', 'Kolkata', 'Mumbai', 'Newdelhi', 'Hyderabad',
       'Noida', 'Calcutta', 'Pune', 'Hyd', 'Bom', 'Bangalore', 'Madras',
       'Gurgaon', 'Gurugram', 'Bengaluru', 'Chennai', 'Bombay', 'Blr',
       'Ggn'], dtype=object)

In [217]:
df['city'].value_counts()

city
Noida        69
Ahmedabad    45
Pune         44
Hyderabad    33
Kolkata      32
Mumbai       29
Chennai      28
Delhi        22
Bengaluru    22
Gurugram     19
Bangalore    19
Calcutta     19
Gurgaon      17
Hyd          13
Madras       11
Newdelhi     11
Bom          10
Blr          10
Ggn           8
Bombay        7
Name: count, dtype: int64

In [218]:
city_aliases = {
    'Bangalore':'Bengaluru',
    'BLR':'Bengaluru',
    'Bombay':'Mumbai',
    'Gurgaon':'Gurugram',
    'Delhi':'New Delhi',
    'Calcutta':'Kolkata',
    'Madras':'Chennai',
    'Bom':'Mumbai',
    'Blr':'Bengaluru',
    'Ggn':'Gurugram',
    'Hyd':'Hyderabad',
    'Newdelhi':'New Delhi'

}

In [219]:
df['city'] = df['city'].replace(city_aliases)
df['city'].sample(10)

411         Pune
147       Mumbai
358    Ahmedabad
385       Mumbai
43        Mumbai
141         Pune
435    Hyderabad
377       Mumbai
307    Hyderabad
106    Ahmedabad
Name: city, dtype: object

In [220]:
df['city'].value_counts()

city
Noida        69
Kolkata      51
Bengaluru    51
Mumbai       46
Hyderabad    46
Ahmedabad    45
Gurugram     44
Pune         44
Chennai      39
New Delhi    33
Name: count, dtype: int64

**4. Standardise industry and funding_stage variants using dicts.**

In [221]:
df['industry'] = df['industry'].str.strip().str.replace('-','').str.replace(' ','').str.title()
df['industry'].unique()

array(['Ecommerce', 'Beautytech', 'Agritech', 'Edtech', 'Foodtech',
       'Saas', 'Traveltech', 'Aiml', 'Healthtech', 'Electricvehicles',
       'Fintech', 'Logistics', 'Proptech', 'Ai/Ml', 'Ev', 'Gaming',
       'Games', 'Ft'], dtype=object)

In [222]:
standardize_industry = {
    'Ft':'Foodtech',
    'Ev':'Electricvehicles',
    'Aiml':'AI/ML',
    'Ai/Ml':'AI/ML',
    'Saas':'SAAS',
    'Healthtech':'HealthTech','Games':'Gaming'
    }
df['industry'] = df['industry'].replace(standardize_industry)

In [223]:
df['industry'].value_counts()

industry
AI/ML               56
Foodtech            42
SAAS                38
Gaming              37
Beautytech          36
Proptech            34
Traveltech          34
HealthTech          33
Ecommerce           33
Agritech            30
Logistics           27
Electricvehicles    27
Edtech              22
Fintech             19
Name: count, dtype: int64

In [224]:
df['funding_stage'].unique()

array(['Series-E', 'Pre-A', 'Pre-Series A', 'Series D', 'SERIES E',
       'Series C', 'Series E', 'ipo', 'Series A', 'PRE-SERIES A',
       'Series B', 'IPO', 'series e', 'PRE-SEED', 'SERIES C', 'Pre-IPO',
       'SEED', 'series_b', 'BRIDGE', 'bridge', 'seed', 'SERIES D',
       'Pre-Seed', 'Bridge', 'Pre Series A', 'series b', 'SERIES B',
       'Preseed', 'Series-D', 'SERIES A', 'Series-B', 'Series-C', 'Seed',
       'series a', 'series d', 'Series-A', 'Pre Seed', 'series_a',
       'series c'], dtype=object)

In [225]:
standardize_funding_state = {
    'SERIES E':'Series E',
    'Series E':'Series E',
    'series e':'Series E',
    'Series-E':"Series E",

    'Pre-A':'Pre-Series A',
    'PRE-SERIES A':'Pre-Series A',
    'Pre Series A':'Pre-Series A',

    'SERIES D':'Series D',
    'Series-D':'Series D',
    'series d':'Series D',

    'SERIES C':'Series C',
    'Series-C':'Series C',
    'series c':'Series C',

    'ipo':'IPO',

    'series_b':'Series B',
    'series b':'Series B',
    'SERIES B':'Series B',
    'Series-B':'Series B',

    'SEED':'Seed',
    'seed':'Seed',

    'SERIES A':'Series A',
    'series a':'Series A',
    'Series-A':'Series A',
    'series_a':'Series A',

    'BRIDGE':'Bridge',
    'bridge':'Bridge',

    'PRE-SEED':'Pre-Seed',
    'Pre Seed':'Pre-Seed',
    'Preseed':'Pre-Seed'
}

In [226]:
df['funding_stage'] = df['funding_stage'].replace(standardize_funding_state)

In [227]:
df['funding_stage'].value_counts()

funding_stage
Series B        58
Series A        49
Seed            49
Series E        48
Pre-Seed        48
Series C        47
Bridge          42
Pre-Series A    41
Series D        40
IPO             34
Pre-IPO         12
Name: count, dtype: int64

**5. Convert amount to numeric (in INR Cr): strip ₹, INR, Cr, Crore, commas, then pd.to_numeric(errors='coerce'). 'Undisclosed' should become NaN.**

In [228]:
df['amount'] = df['amount'].str.strip().str.replace(' ','').str.replace('₹','').str.replace('INR','').str.replace('Crore','').str.replace('Cr','')

In [229]:
df['amount'] = pd.to_numeric(df['amount'],errors='coerce')

In [230]:
print(f'The dtype of column: {df['amount'].dtypes}')

The dtype of column: float64

**6. Convert funding_date to datetime with errors='coerce' and dayfirst=True.**

In [231]:
df['funding_date'] = pd.to_datetime(df['funding_date'],errors='coerce',dayfirst=True)

In [232]:
df['funding_date']

0     2024-02-29
1     2018-08-18
2            NaT
3     2018-03-31
4            NaT
         ...
463   2012-07-09
464          NaT
465          NaT
466          NaT
467          NaT
Name: funding_date, Length: 468, dtype: datetime64[ns]

**7. Drop duplicate rows.**

In [233]:
df = df.drop_duplicates()
df

,startup_name,city,industry,funding_stage,amount,funding_date,investors,founded_year
0,Playtimegames,New Delhi,Ecommerce,Series E,942.0,2024-02-29,"Ranjan Pai, Prosus Ventures",2020.0
1,Rebelfoods,Ahmedabad,Beautytech,Pre-Series A,1440.0,2018-08-18,Lightspeed,2017.0
2,Freshworks,Kolkata,Agritech,Pre-Series A,329.0,NaT,Info Edge,2020.0
3,Bigbasket,Mumbai,Ecommerce,Series D,1405.0,2018-03-31,B Capital,2016.0
4,Ola,Kolkata,Edtech,Series E,2223.0,NaT,Falcon Edge,2017.0
...,...,...,...,...,...,...,...,...
462,Rebelfoods,Hyderabad,Agritech,Series B,157.0,NaT,Matrix Partners,2017.0
463,Doubtnut,Kolkata,Ecommerce,Seed,88.0,2012-07-09,"Elevation Capital, Chiratae Ventures",2010.0
464,Ecomotor,Kolkata,HealthTech,Seed,41.0,NaT,"Goldman Sachs, 3one4 Capital, Elevation Capita...",2008.0
466,Fasttracklogistics,Kolkata,Agritech,Bridge,700.0,NaT,"Matrix Partners, Blume Ventures",2018.0
467,Freshworks,Kolkata,Fintech,Seed,468.0,NaT,"Norwest Venture, Elevation Capital, Blume Vent...",2016.0

# **Using cleaned_df for question 17 onwards as suggested in the pdf**


**Loading & Inspection (Q17 to Q19)**

**Q17. After loading the raw CSV (before cleaning), answer:**

**(a) How many rows and columns?**

**(b) How many missing values are in each column?**

**(c) How many exact duplicate rows are present?**

In [234]:
cleaned_df = pd.read_csv('indian_startups_fundingDADS.csv')
cleaned_df

,Startup Name,City,INDUSTRY,Funding Stage,Amount,Funding Date,Investors,Founded Year
0,PlayTime Games,DELHI,ecommerce,Series-E,INR 942 Crore,29/02/2024,"Ranjan Pai, Prosus Ventures",2020.0
1,Rebel Foods,ahmedabad,BeautyTech,Pre-A,1440,18/08/2018,Lightspeed,2017.0
2,Freshworks,Kolkata,AgriTech,Pre-Series A,329 Cr,14 Jul 2020,Info Edge,2020.0
3,BigBasket,Mumbai,ecommerce,Series D,₹1405 Cr,31/03/2018,B Capital,2016.0
4,Ola,KOLKATA,EdTech,SERIES E,₹2223 Cr,24-08-2021,Falcon Edge,2017.0
...,...,...,...,...,...,...,...,...
463,Doubtnut,KOLKATA,ecommerce,Seed,88 Cr,09/07/2012,"Elevation Capital, Chiratae Ventures",2010.0
464,EcoMotor,KOLKATA,HealthTech,Seed,₹41 Cr,01-03-2019,"Goldman Sachs, 3one4 Capital, Elevation Capita...",2008.0
465,Zepto,CHENNAI,AI-ML,Bridge,24 Cr,2023/11/24,"Blume Ventures, Inventus Capital",2018.0
466,FastTrack Logistics,KOLKATA,Agri Tech,bridge,INR 700 Crore,08 Dec 2019,"Matrix Partners, Blume Ventures",2018.0
467,Freshworks,Calcutta,fintech,seed,₹468 Cr,NaN,"Norwest Venture, Elevation Capital, Blume Vent...",2016.0

In [235]:
print(f'Total Rows:{cleaned_df.shape[0]}')
print(f'Total Columns:{cleaned_df.shape[1]}')
print(f'Missing values in each column:{cleaned_df.isna().sum()}')
print(f'Exact dupilcate rows:{cleaned_df.duplicated().sum()}')

Total Rows:468
Total Columns:8
Missing values in each column:Startup Name      0
City              0
INDUSTRY          0
Funding Stage     0
Amount            0
Funding Date     19
Investors        10
Founded Year     23
dtype: int64
Exact dupilcate rows:18

**Q18. After cleaning column names to snake_case, print the cleaned column names sorted alphabetically. Don't manually type them – use Python on df.columns.**

In [236]:
cleaned_df =cleaned_df.rename(columns = {
    'Startup Name ':'startup_name',
    'City':'city',
    'INDUSTRY':'industry',
    'Funding Stage':'funding_stage',
    'Amount':'amount',
    'Funding Date':'funding_date',
    'Investors':'investors',
    'Founded Year':'founded_year'
})

In [237]:
sorted(cleaned_df.columns)

['amount',
 'city',
 'founded_year',
 'funding_date',
 'funding_stage',
 'industry',
 'investors',
 'startup_name']

**Q19. Without using .describe(), compute these statistics on the cleaned founded_year column (after
dropping NaN): count, mean, min, max, median, std. Print as a single dictionary with these exact keys.**

In [238]:
cleaned_df = cleaned_df.dropna(subset=["founded_year"])
aggregate_functions = {
    'count':cleaned_df['founded_year'].count(),
    'mean':cleaned_df['founded_year'].mean(),
    'min':cleaned_df['founded_year'].min(),
    'max':cleaned_df['founded_year'].max(),
    'median':cleaned_df['founded_year'].median(),
    'Standard Deviation':cleaned_df['founded_year'].std()
}
for function,value in aggregate_functions.items():
  print(f'{function}:{value:.2f}')

count:445.00
mean:2016.46
min:2008.00
max:2022.00
median:2017.00
Standard Deviation:4.19

**Cleaning Verification (Q20 to Q24)**

**Q20. After cleaning the city column with the aliases mapped, print all unique city names sorted alphabetically. There should be exactly 10 cities and no duplicates from case or whitespace.**

In [239]:
cleaned_df['startup_name'] = cleaned_df['startup_name'].str.strip().str.replace(' ','').str.title()
cleaned_df['city'] = cleaned_df['city'].str.strip().str.replace(' ','').str.title()

In [240]:
cleaned_df['startup_name'].sample(10)

249         Swiggy
55         Blinkit
432      Boldfoods
115      Ruralkart
33     Mediconnect
22          Byju'S
138      Docontime
325      Beautybox
86       Tutormate
371    Greenwheels
Name: startup_name, dtype: object

In [241]:
cleaned_df['city'].unique()

array(['Delhi', 'Ahmedabad', 'Kolkata', 'Mumbai', 'Newdelhi', 'Hyderabad',
       'Noida', 'Calcutta', 'Pune', 'Hyd', 'Bom', 'Bangalore', 'Madras',
       'Gurgaon', 'Gurugram', 'Bengaluru', 'Chennai', 'Bombay', 'Blr',
       'Ggn'], dtype=object)

In [242]:
cleaned_df['city'].value_counts()

city
Noida        68
Ahmedabad    43
Pune         41
Kolkata      32
Hyderabad    31
Mumbai       28
Chennai      24
Delhi        20
Bengaluru    20
Gurugram     19
Bangalore    18
Calcutta     18
Gurgaon      17
Hyd          12
Madras       11
Blr          10
Bom           9
Newdelhi      9
Ggn           8
Bombay        7
Name: count, dtype: int64

In [243]:
city_aliases = {
    'Bangalore':'Bengaluru',
    'BLR':'Bengaluru',
    'Bombay':'Mumbai',
    'Gurgaon':'Gurugram',
    'Delhi':'New Delhi',
    'Calcutta':'Kolkata',
    'Madras':'Chennai',
    'Bom':'Mumbai',
    'Blr':'Bengaluru',
    'Ggn':'Gurugram',
    'Hyd':'Hyderabad',
    'Newdelhi':'New Delhi'

}

In [244]:
cleaned_df['city'] = cleaned_df['city'].replace(city_aliases)
cleaned_df['city'].sample(10)

217        Noida
133    Hyderabad
398    Bengaluru
35        Mumbai
49       Chennai
364      Kolkata
413      Chennai
454    Hyderabad
5      New Delhi
319        Noida
Name: city, dtype: object

In [245]:
cleaned_df['city'].value_counts()

city
Noida        68
Kolkata      50
Bengaluru    48
Mumbai       44
Gurugram     44
Ahmedabad    43
Hyderabad    43
Pune         41
Chennai      35
New Delhi    29
Name: count, dtype: int64

**There should be exactly 10 cities and no duplicates from case or whitespace.**

In [246]:
sorted(cleaned_df['city'].unique())

['Ahmedabad',
 'Bengaluru',
 'Chennai',
 'Gurugram',
 'Hyderabad',
 'Kolkata',
 'Mumbai',
 'New Delhi',
 'Noida',
 'Pune']

**Q21. After standardising the industry column using a dict, print the count of startups per industry sorted from most to least common (use value_counts()).**

In [247]:
cleaned_df['industry'] = cleaned_df['industry'].str.strip().str.replace('-','').str.replace(' ','').str.title()
cleaned_df['industry'].unique()

array(['Ecommerce', 'Beautytech', 'Agritech', 'Edtech', 'Foodtech',
       'Saas', 'Traveltech', 'Aiml', 'Healthtech', 'Electricvehicles',
       'Fintech', 'Logistics', 'Proptech', 'Ai/Ml', 'Ev', 'Gaming',
       'Games', 'Ft'], dtype=object)

In [248]:
standardize_industry = {
    'Ft':'Foodtech',
    'Ev':'Electricvehicles',
    'Aiml':'AI/ML',
    'Ai/Ml':'AI/ML',
    'Saas':'SAAS',
    'Healthtech':'HealthTech','Games':'Gaming'
    }
cleaned_df['industry'] = cleaned_df['industry'].replace(standardize_industry)

**The count of startups per industry sorted from most to least common (use value_counts())**

In [249]:
cleaned_df['industry'].value_counts()

industry
AI/ML               53
Foodtech            39
SAAS                38
Gaming              34
Proptech            34
Traveltech          33
Beautytech          32
HealthTech          31
Ecommerce           31
Agritech            29
Electricvehicles    27
Logistics           24
Edtech              22
Fintech             18
Name: count, dtype: int64

**Q22. After converting amount to numeric, print:**

**(a) The dtype of the column**

**(b) How many NaN values are there (from 'Undisclosed' entries)**

**(c) The mean funding amount (ignoring NaN)**

**(d) The minimum and maximum funding amount**

In [250]:
cleaned_df['amount'] = cleaned_df['amount'].str.strip().str.replace(' ','').str.replace('₹','').str.replace('INR','').str.replace('Crore','').str.replace('Cr','')

In [251]:
cleaned_df['amount'] = pd.to_numeric(cleaned_df['amount'],errors='coerce')

In [252]:
print(f'The dtype of column: {cleaned_df['amount'].dtypes}')

The dtype of column: float64

In [253]:
print(f'The total number of NaN values: {cleaned_df['amount'].isna().sum()}')

The total number of NaN values: 36

In [254]:
print(f'The mean funding amount (ignoring NaN): {cleaned_df['amount'].mean():.2f} ')

The mean funding amount (ignoring NaN): 718.53

In [255]:
print(f'The minimum funding amount: {cleaned_df['amount'].min()}')
print(f'The maximum funding amount: {cleaned_df['amount'].max()}')

The minimum funding amount: 1.0
The maximum funding amount: 3549.0

**Q23. After converting funding_date to datetime:**

**(a) Count how many deals happened in each year. Use .dt.year.**

**(b) Print the year with the highest number of funding deals.**

In [256]:
cleaned_df['funding_date'] = pd.to_datetime(cleaned_df['funding_date'],errors='coerce',dayfirst=True)

In [257]:
cleaned_df['funding_date']

0     2024-02-29
1     2018-08-18
2            NaT
3     2018-03-31
4            NaT
         ...
463   2012-07-09
464          NaT
465          NaT
466          NaT
467          NaT
Name: funding_date, Length: 445, dtype: datetime64[ns]

In [258]:
print(f'The number of deals that happened in each year: \n{cleaned_df['funding_date'].dt.year.value_counts()}')

The number of deals that happened in each year:
funding_date
2022.0    24
2021.0    14
2023.0    13
2019.0     7
2020.0     6
2024.0     6
2018.0     4
2017.0     3
2015.0     3
2016.0     2
2011.0     1
2014.0     1
2013.0     1
2012.0     1
Name: count, dtype: int64

In [259]:
print(f'The year with the highest number of funding deals: {cleaned_df['funding_date'].dt.year.value_counts().head(1)}')

The year with the highest number of funding deals: funding_date
2022.0    24
Name: count, dtype: int64

**Q24. After standardising funding_stage, print the count of startups per stage (sorted from most common to least).**

In [260]:
cleaned_df['funding_stage'].unique()

array(['Series-E', 'Pre-A', 'Pre-Series A', 'Series D', 'SERIES E',
       'Series C', 'Series E', 'ipo', 'Series A', 'PRE-SERIES A',
       'Series B', 'IPO', 'series e', 'PRE-SEED', 'SERIES C', 'Pre-IPO',
       'SEED', 'series_b', 'BRIDGE', 'bridge', 'seed', 'SERIES D',
       'Pre-Seed', 'Bridge', 'Pre Series A', 'series b', 'SERIES B',
       'Preseed', 'Series-D', 'SERIES A', 'Series-B', 'Series-C', 'Seed',
       'series a', 'series d', 'Series-A', 'Pre Seed', 'series_a',
       'series c'], dtype=object)

In [261]:
standardize_funding_state = {
    'SERIES E':'Series E',
    'Series E':'Series E',
    'series e':'Series E',
    'Series-E':"Series E",

    'Pre-A':'Pre-Series A',
    'PRE-SERIES A':'Pre-Series A',
    'Pre Series A':'Pre-Series A',

    'SERIES D':'Series D',
    'Series-D':'Series D',
    'series d':'Series D',

    'SERIES C':'Series C',
    'Series-C':'Series C',
    'series c':'Series C',

    'ipo':'IPO',

    'series_b':'Series B',
    'series b':'Series B',
    'SERIES B':'Series B',
    'Series-B':'Series B',

    'SEED':'Seed',
    'seed':'Seed',

    'SERIES A':'Series A',
    'series a':'Series A',
    'Series-A':'Series A',
    'series_a':'Series A',

    'BRIDGE':'Bridge',
    'bridge':'Bridge',

    'PRE-SEED':'Pre-Seed',
    'Pre Seed':'Pre-Seed',
    'Preseed':'Pre-Seed'

}
cleaned_df['funding_stage'] = cleaned_df['funding_stage'].replace(standardize_funding_state)

In [262]:
cleaned_df['funding_stage'].value_counts()

funding_stage
Series B        56
Series E        48
Series A        47
Pre-Seed        47
Seed            46
Series C        42
Bridge          40
Pre-Series A    39
Series D        36
IPO             32
Pre-IPO         12
Name: count, dtype: int64

In [263]:
cleaned_df = cleaned_df.drop_duplicates()

In [264]:
cleaned_df

,startup_name,city,industry,funding_stage,amount,funding_date,investors,founded_year
0,Playtimegames,New Delhi,Ecommerce,Series E,942.0,2024-02-29,"Ranjan Pai, Prosus Ventures",2020.0
1,Rebelfoods,Ahmedabad,Beautytech,Pre-Series A,1440.0,2018-08-18,Lightspeed,2017.0
2,Freshworks,Kolkata,Agritech,Pre-Series A,329.0,NaT,Info Edge,2020.0
3,Bigbasket,Mumbai,Ecommerce,Series D,1405.0,2018-03-31,B Capital,2016.0
4,Ola,Kolkata,Edtech,Series E,2223.0,NaT,Falcon Edge,2017.0
...,...,...,...,...,...,...,...,...
462,Rebelfoods,Hyderabad,Agritech,Series B,157.0,NaT,Matrix Partners,2017.0
463,Doubtnut,Kolkata,Ecommerce,Seed,88.0,2012-07-09,"Elevation Capital, Chiratae Ventures",2010.0
464,Ecomotor,Kolkata,HealthTech,Seed,41.0,NaT,"Goldman Sachs, 3one4 Capital, Elevation Capita...",2008.0
466,Fasttracklogistics,Kolkata,Agritech,Bridge,700.0,NaT,"Matrix Partners, Blume Ventures",2018.0
467,Freshworks,Kolkata,Fintech,Seed,468.0,NaT,"Norwest Venture, Elevation Capital, Blume Vent...",2016.0

**Filtering (Q25 to Q28)**

**Q25. Find all Bengaluru-based startups with funding amount > 100 Cr. Print the startup_name and amount columns, sorted by amount descending.**

In [265]:
cleaned_df[cleaned_df['amount']>100][['startup_name','amount']].sort_values('amount',ascending=False)

     startup_name  amount
179     Wealthwiz  3549.0
333     Fitfusion  3546.0
110        Studyo  3545.0
246   Fitnessplus  3545.0
28       Rupaypro  3541.0
..            ...     ...
108  Urbancompany   112.0
97    Brightspark   111.0
163         Mediq   111.0
140  Urbancompany   108.0
156        Practo   103.0

[270 rows x 2 columns]

**Q26. Using .isin(), find startups whose industry is one of: Fintech, Edtech, HealthTech. Print the total count.**

In [266]:
industry = ['Fintech','Edtech','HealthTech']
isin_function = cleaned_df['industry'].isin(industry).value_counts()
print(f"Total count of startups in Fintech, Edtech, or HealthTech: {isin_function.get(True)}")

Total count of startups in Fintech, Edtech, or HealthTech: 68

**Q27. Using .between(), find startups founded between 2015 and 2020 (both inclusive). Print the count.
Be careful – founded_year has missing values.**

In [267]:
print(f'Startups founded between 2015 and 2020 (both inclusive): {cleaned_df['founded_year'].between(2015,2020).value_counts().get(True)}')

Startups founded between 2015 and 2020 (both inclusive): 211

**Q28. Using .str.contains() with case=False and na=False, find all startups whose name contains the word 'pay'. Print the unique names.**

In [268]:
startups_with_pay = cleaned_df[cleaned_df['startup_name'].str.contains(r'pay', case=False, na=False)]
print(startups_with_pay['startup_name'].unique())

['Rupaypro' 'Razorpay' 'Paytm' 'Quickpayindia' 'Paybuddy']

**Transformation & Derived Columns (Q29 to Q32)**

**Q29. Add a new column funding_efficiency = amount / (2024 - founded_year). Higher = raised more capital per year of existence. Sort by funding_efficiency descending. Print top 10 with name, industry, amount, founded_year, and funding_efficiency.**

In [269]:
cleaned_df['funding_efficiency'] = cleaned_df['amount']/cleaned_df['founded_year']
funding_efficiency = cleaned_df[['startup_name','industry','amount','founded_year','funding_efficiency']].sort_values('funding_efficiency',ascending=False)

top_10_name = funding_efficiency.head(10)
top_10_name

    startup_name          industry  amount  founded_year  funding_efficiency
179    Wealthwiz            Gaming  3549.0        2008.0            1.767430
110       Studyo          Foodtech  3545.0        2014.0            1.760179
333    Fitfusion            Edtech  3546.0        2017.0            1.758057
170      Curefit         Ecommerce  3540.0        2015.0            1.756824
175     Propmart            Edtech  3534.0        2012.0            1.756461
311     Routemap  Electricvehicles  3528.0        2010.0            1.755224
246  Fitnessplus           Fintech  3545.0        2020.0            1.754950
28      Rupaypro        Traveltech  3541.0        2019.0            1.753839
12           Ola  Electricvehicles  3520.0        2008.0            1.752988
226  Agriconnect        Traveltech  3526.0        2014.0            1.750745

**Q30. Using .apply() with a lambda, add a funding_tier column based on amount:**

**amount ≥ 1000 Cr → 'Unicorn'**

**amount ≥ 500 Cr → 'Mega'**

**amount ≥ 100 Cr → 'Large'**

**amount ≥ 10 Cr → 'Mid'**

**else (including NaN) → 'Small / Unknown'**

**Print the count of startups in each tier.**

In [270]:
cleaned_df['funding_tier'] = cleaned_df['amount'].apply(lambda x: 'Unicorn' if x>=1000 else 'Mega' if x>=500 else 'Large' if x>=100 else 'Mid' if x>=10 else 'Small/Unkonown')

In [271]:
cleaned_df['funding_tier'].value_counts()

funding_tier
Large             122
Mid               112
Unicorn            83
Mega               66
Small/Unkonown     44
Name: count, dtype: int64

**Q31. Using pd.cut(), bin founded_year into 3 eras:**

**Before 2010 → 'Early'**

**2010 to 2017 → 'Growth'**

**2018 and later → 'Recent'**

**Print the count of startups in each era.**

In [272]:
labels = ['Early','Growth','Recent']

boundaries = [0, 2009, 2017, cleaned_df['founded_year'].max() + 1]
cleaned_df['era'] = pd.cut(cleaned_df['founded_year'],bins = boundaries,labels = labels, right=True)
cleaned_df['era'].value_counts()

era
Recent    207
Growth    195
Early      25
Name: count, dtype: int64

**Q32. The investors column has multiple investors separated by ', ' (comma + space). Create a new column investor_count showing the number of investors per startup. Use .apply() with a lambda. Handle NaN values (count = 0). Print the value_counts() of investor_count.**

In [273]:
cleaned_df['investor_count'] = cleaned_df['investors'].apply(lambda x: len(x.split(', ')) if pd.notnull(x) else 0)

In [274]:
cleaned_df['investor_count'].value_counts().sort_index(ascending=False)

investor_count
4     25
3    111
2    188
1     93
0     10
Name: count, dtype: int64

**Aggregation & Grouping (Q33 to Q37)**

**Q33. Compute the average funding amount per industry (ignoring NaN). Sort descending. Print the top 5 industries by average funding.**

In [275]:
cleaned_df.groupby('industry')['amount'].mean().sort_values(ascending=False).head(5)

industry
Fintech             1249.058824
Edtech              1179.052632
Traveltech          1129.806452
Electricvehicles    1090.769231
Gaming               933.928571
Name: amount, dtype: float64

**Q34. For each city, compute three metrics in a single groupby using .agg() with a dictionary:**

**(a) Number of startups**

**(b) Total funding raised (sum of amount)**

**(c) Average funding per startup**

**Print the top 10 cities by number of startups.**

In [276]:
city_metrics = cleaned_df.groupby('city').agg(
    Number_of_startup=('startup_name', 'count'),
    total_funding=('amount', 'sum'),
    avg_funding=('amount', 'mean')
)
city_metrics.sort_values(by='Number_of_startup', ascending=False).head(10)

           Number_of_startup  total_funding  avg_funding
city
Noida                     61        35670.0   648.545455
Kolkata                   50        28230.0   613.695652
Bengaluru                 46        34240.0   815.238095
Gurugram                  44        29757.0   725.780488
Mumbai                    43        28359.0   746.289474
Ahmedabad                 42        26617.0   633.738095
Hyderabad                 40        23636.0   675.314286
Pune                      39        32702.0   908.388889
Chennai                   33        17765.0   555.156250
New Delhi                 29        27723.0  1066.269231

**Q35. Interview-style. Which industry has the highest average funding, but only considering industries with at least 15 startups? (Sparse industries bias the mean.) Print industry name, count, and average funding.**

In [277]:
highest_average_funding = cleaned_df.groupby('industry').agg(
    Total_startups_per_industry=('startup_name','count'),
    Average_funding=('amount','mean')
    )
highest_average_funding.sort_values(by='Total_startups_per_industry',ascending=False)

                  Total_startups_per_industry  Average_funding
industry
AI/ML                                      51       537.520833
Foodtech                                   39       719.277778
SAAS                                       36       577.485714
Traveltech                                 33      1129.806452
Proptech                                   32       388.821429
Gaming                                     31       933.928571
Beautytech                                 30       678.357143
HealthTech                                 29       386.185185
Ecommerce                                  28       823.500000
Agritech                                   28       292.269231
Electricvehicles                           27      1090.769231
Logistics                                  24       618.090909
Edtech                                     21      1179.052632
Fintech                                    18      1249.058824

**Q36. Using pd.crosstab(), show the distribution of funding_tier across the top 5 industries by count.Rows = industry, columns = funding_tier, values = count of startups.**

In [278]:
top_5_industries = cleaned_df['industry'].value_counts().head(5).index
distribution_of_funding_tier = pd.crosstab(index=cleaned_df[cleaned_df['industry'].isin(top_5_industries)]['industry'], columns=cleaned_df['funding_tier'])
display(distribution_of_funding_tier)

funding_tier  Large  Mega  Mid  Small/Unkonown  Unicorn
industry
AI/ML            12     6   18               6        9
Foodtech         11     7   11               3        7
Proptech         13     6    7               4        2
SAAS             11     4   11               3        7
Traveltech       11     6    4               2       10

**Q37. For each industry, find the startup with the highest funding amount. Print startup_name, industry,
city, and amount. Hint: groupby + idxmax() on amount.**

In [279]:
idx = cleaned_df.groupby('industry')['amount'].idxmax()
highest_funded_startups_per_industry = cleaned_df.loc[idx, ['startup_name', 'industry', 'city', 'amount']]
display(highest_funded_startups_per_industry.sort_values(by='amount', ascending=False))

    startup_name          industry       city  amount
179    Wealthwiz            Gaming    Kolkata  3549.0
333    Fitfusion            Edtech     Mumbai  3546.0
246  Fitnessplus           Fintech  New Delhi  3545.0
110       Studyo          Foodtech   Gurugram  3545.0
28      Rupaypro        Traveltech  Ahmedabad  3541.0
170      Curefit         Ecommerce     Mumbai  3540.0
118        Paytm  Electricvehicles       Pune  3533.0
93     Vitalcare        Beautytech       Pune  3522.0
322   Classroomx             AI/ML  Ahmedabad  3520.0
123        Nykaa         Logistics  New Delhi  3515.0
56    Whitehatjr              SAAS  Hyderabad  2250.0
386   Investedge        HealthTech    Kolkata  2219.0
195    Boldfoods          Agritech  Hyderabad  1449.0
228         Boat          Proptech  New Delhi  1438.0

**Real Industry Problems (Q38 to Q40)**

**Q38. Emerging player finder. An 'emerging player' is a startup founded in 2019 or later, with funding ≥
100 Cr, in one of Fintech / Edtech / HealthTech. Find all of them, sort by amount descending, print
name, industry, city, founded_year, and amount. Why might a VC analyst care about this list?**

In [280]:
cleaned_df[cleaned_df['founded_year']==2019][cleaned_df['amount']>=100][cleaned_df['industry'].isin(['Fintech','Edtech','HealthTech'])][['startup_name','industry','city','founded_year','amount']].sort_values('amount',ascending=False)

/tmp/ipykernel_482/389247554.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cleaned_df[cleaned_df['founded_year']==2019][cleaned_df['amount']>=100][cleaned_df['industry'].isin(['Fintech','Edtech','HealthTech'])][['startup_name','industry','city','founded_year','amount']].sort_values('amount',ascending=False)
/tmp/ipykernel_482/389247554.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cleaned_df[cleaned_df['founded_year']==2019][cleaned_df['amount']>=100][cleaned_df['industry'].isin(['Fintech','Edtech','HealthTech'])][['startup_name','industry','city','founded_year','amount']].sort_values('amount',ascending=False)

    startup_name    industry       city  founded_year  amount
57     Learnlive     Fintech      Noida        2019.0  3512.0
461      Postman      Edtech  Hyderabad        2019.0  1404.0
130    Dermaplus  HealthTech   Gurugram        2019.0   711.0
334     Shopeasy     Fintech   Gurugram        2019.0   489.0
290       Zomato  HealthTech   Gurugram        2019.0   322.0

A VC (Venture Capital) Analyst is a job who searches for successful startups and analyzing them is their job so they care about this list

**Q39. Investor hub analysis. A foreign investor wants to know which Indian city has the highest TOTAL
funding raised, considering only cities with at least 20 startups (so the number is meaningful). Print city name, count, and total funding.**

In [281]:
idx = cleaned_df.groupby('city')['amount'].idxmax()
count = cleaned_df.groupby('city').agg(count=('startup_name','count'))

count.sort_values(by='count',ascending=False)
Investor_hub_analysis = count[count['count']>=20].merge(cleaned_df.loc[idx,['city','amount']],on='city').sort_values(by='amount',ascending=False)
Investor_hub_analysis

        city  count  amount
5    Kolkata     50  3549.0
6     Mumbai     43  3546.0
7  New Delhi     29  3545.0
3   Gurugram     44  3545.0
0  Ahmedabad     42  3541.0
9       Pune     39  3533.0
1  Bengaluru     46  3528.0
8      Noida     61  3521.0
4  Hyderabad     40  2250.0
2    Chennai     33  2249.0

**Q40. Market saturation. For each combination of (city, industry), count the number of startups. Print the top 10 most-saturated combinations. This tells a new founder where competition is most intense – and by elimination, where the gaps might be.**

In [282]:
no_of_startups_for_city_and_industry = cleaned_df.groupby(['city','industry']).agg(count=('startup_name','count'))
no_of_startups_for_city_and_industry.sort_values(by='count',ascending=False).head(10)

                      count
city      industry
Gurugram  Foodtech       11
Mumbai    AI/ML           8
Kolkata   AI/ML           7
Bengaluru Gaming          7
Noida     Foodtech        7
Pune      AI/ML           7
Noida     Traveltech      7
Kolkata   SAAS            7
Hyderabad SAAS            7
Ahmedabad AI/ML           6

In [283]:
cleaned_df

,startup_name,city,industry,funding_stage,amount,funding_date,investors,founded_year,funding_efficiency,funding_tier,era,investor_count
0,Playtimegames,New Delhi,Ecommerce,Series E,942.0,2024-02-29,"Ranjan Pai, Prosus Ventures",2020.0,0.466337,Mega,Recent,2
1,Rebelfoods,Ahmedabad,Beautytech,Pre-Series A,1440.0,2018-08-18,Lightspeed,2017.0,0.713932,Unicorn,Growth,1
2,Freshworks,Kolkata,Agritech,Pre-Series A,329.0,NaT,Info Edge,2020.0,0.162871,Large,Recent,1
3,Bigbasket,Mumbai,Ecommerce,Series D,1405.0,2018-03-31,B Capital,2016.0,0.696925,Unicorn,Growth,1
4,Ola,Kolkata,Edtech,Series E,2223.0,NaT,Falcon Edge,2017.0,1.102132,Unicorn,Growth,1
...,...,...,...,...,...,...,...,...,...,...,...,...
462,Rebelfoods,Hyderabad,Agritech,Series B,157.0,NaT,Matrix Partners,2017.0,0.077838,Large,Growth,1
463,Doubtnut,Kolkata,Ecommerce,Seed,88.0,2012-07-09,"Elevation Capital, Chiratae Ventures",2010.0,0.043781,Mid,Growth,2
464,Ecomotor,Kolkata,HealthTech,Seed,41.0,NaT,"Goldman Sachs, 3one4 Capital, Elevation Capita...",2008.0,0.020418,Mid,Early,4
466,Fasttracklogistics,Kolkata,Agritech,Bridge,700.0,NaT,"Matrix Partners, Blume Ventures",2018.0,0.346878,Mega,Recent,2
467,Freshworks,Kolkata,Fintech,Seed,468.0,NaT,"Norwest Venture, Elevation Capital, Blume Vent...",2016.0,0.232143,Large,Growth,3

# ==========================================END===================================================================

..